-- MySQL Script generated by MySQL Workbench
-- Thu May 8 23:29:28 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

DROP SCHEMA IF EXISTS mydb;
CREATE SCHEMA mydb 
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_general_ci;
USE mydb;

-- -------------------------------
-- Tabela Fornecedor
-- -------------------------------
CREATE TABLE Fornecedor (
  Id INT NOT NULL PRIMARY KEY,
  Nome VARCHAR(120) NOT NULL,
  Endereco VARCHAR(120) NOT NULL,
  CEP VARCHAR(10) NOT NULL,
  Bairro VARCHAR(50),
  Logradouro VARCHAR(100) NOT NULL,
  Numero INT,
  Observacoes VARCHAR(240),
  Data_Inclusao DATETIME NOT NULL,
  Data_Exclusao DATETIME
)ENGINE=InnoDB;

-- -------------------------------
-- Tabela Usuario
-- -------------------------------
CREATE TABLE Usuario (
  Id INT NOT NULL PRIMARY KEY,
  Nome VARCHAR(120) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  Endereco VARCHAR(120) NOT NULL,
  CEP VARCHAR(10) NOT NULL,
  Bairro VARCHAR(50),
  Logradouro VARCHAR(100) NOT NULL,
  Numero INT,
  Login VARCHAR(100) NOT NULL,
  Senha VARCHAR(255) NOT NULL,
  Data_Inclusao DATETIME NOT NULL,
  Data_Exclusao DATETIME
)ENGINE=InnoDB;

-- -------------------------------
-- Tabela Cliente
-- -------------------------------
CREATE TABLE Cliente (
  Id INT NOT NULL PRIMARY KEY,
  Nome VARCHAR(120) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  Endereco VARCHAR(120) NOT NULL,
  CEP VARCHAR(10) NOT NULL,
  Bairro VARCHAR(50),
  Logradouro VARCHAR(100) NOT NULL,
  Numero INT,
  Data_Inclusao DATETIME NOT NULL,
  Data_Exclusao DATETIME
)ENGINE=InnoDB;

-- -------------------------------
-- Tabela Categoria
-- -------------------------------
CREATE TABLE Categoria (
  Id INT NOT NULL PRIMARY KEY,
  Nome VARCHAR(45) NOT NULL,
  Descricao VARCHAR(120) NOT NULL,
  Data_Inclusao DATETIME NOT NULL,
  Data_Exclusao DATETIME 
)ENGINE=InnoDB;

-- -------------------------------
-- Tabela Produto
-- -------------------------------
CREATE TABLE Produto (
  Id INT NOT NULL PRIMARY KEY,
  Nome VARCHAR(45) NOT NULL,
  Descricao VARCHAR(120) NOT NULL,
  Quantidade INT NOT NULL,
  Disponivel BIT NOT NULL,
  Data_Inclusao DATETIME NOT NULL,
  Data_Exclusao DATETIME,
  Data_Validade VARCHAR(45) NOT NULL,
  Preco DOUBLE NOT NULL,
  Link_Foto VARCHAR(80),
  Categoria_Id INT NOT NULL,
  CONSTRAINT fk_Produto_Categoria1 FOREIGN KEY (Categoria_Id)
    REFERENCES Categoria(Id)
    ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE=InnoDB;

-- -------------------------------
-- Tabela Pedido_Compra
-- -------------------------------
CREATE TABLE Pedido_Compra (
  Id INT NOT NULL PRIMARY KEY,
  Valor DOUBLE NOT NULL,
  NotaFiscal VARCHAR(50) NOT NULL,
  Data_Atualizacao DATETIME,
  Fornecedor_Id INT NOT NULL,
  Usuario_Id INT NOT NULL,
  CONSTRAINT fk_Pedido_Compra_Fornecedor1 FOREIGN KEY (Fornecedor_Id)
    REFERENCES Fornecedor(Id)
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_Pedido_Compra_Usuario1 FOREIGN KEY (Usuario_Id)
    REFERENCES Usuario(Id)
    ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE=InnoDB;

-- -------------------------------
-- Tabela Venda (Cliente compra, Usuario vende)
-- -------------------------------
CREATE TABLE Venda (
  Id INT NOT NULL PRIMARY KEY,
  Data_Pedido DATETIME NOT NULL,
  Observacoes VARCHAR(240),
  Valor_Total DOUBLE,
  Cliente_Id INT NOT NULL,
  Usuario_Id INT NOT NULL,
  CONSTRAINT fk_Venda_Cliente FOREIGN KEY (Cliente_Id)
    REFERENCES Cliente(Id)
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_Venda_Usuario FOREIGN KEY (Usuario_Id)
    REFERENCES Usuario(Id)
    ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE=InnoDB;

-- -------------------------------
-- Tabela Item_Venda
-- -------------------------------
CREATE TABLE Item_Venda (
  Venda_Id INT NOT NULL,
  Produto_Id INT NOT NULL,
  Valor_Unitario DOUBLE NOT NULL,  
  Quantidade INT NOT NULL,
  Valor_Total DOUBLE GENERATED ALWAYS AS (`Valor_Unitario` * `Quantidade`) STORED,
  PRIMARY KEY (Venda_Id, Produto_Id),
  CONSTRAINT fk_Item_Venda_Venda FOREIGN KEY (Venda_Id)
    REFERENCES Venda(Id)
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_Item_Venda_Produto FOREIGN KEY (Produto_Id)
    REFERENCES Produto(Id)
    ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE=InnoDB;

-- -------------------------------
-- Tabela Estoque
-- -------------------------------
CREATE TABLE Estoque (
  Id VARCHAR(100) NOT NULL PRIMARY KEY,
  Quantidade VARCHAR(50) NOT NULL,
  Produto_Id INT NOT NULL,
  Categoria_Id INT NOT NULL,
  Fornecedor_Id INT NOT NULL,
  CONSTRAINT fk_Estoque_Produto FOREIGN KEY (Produto_Id)
    REFERENCES Produto(Id)
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_Estoque_Categoria FOREIGN KEY (Categoria_Id)
    REFERENCES Categoria(Id)
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_Estoque_Fornecedor FOREIGN KEY (Fornecedor_Id)
    REFERENCES Fornecedor(Id)
    ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE=InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
